name: Install test
on: [pull_request]
#  schedule:
#    - cron: "0 11 * * 1"
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Initialize React Native app
      run: npx react-native init MyRealmApp
    - name: Install latest Realm JS
      run: npm install realm
      working-directory: MyRealmApp
    - name: Manually link Realm
      run: npx react-native link realm
      working-directory: MyRealmApp
    - name: Copying scripts
      run: cp ./tests/install-test/* ./MyRealmApp
    - name: Start the app
      run: npx react-native run-ios
      working-directory: MyRealmApp
    - name: Wait for app
      run: node wait-for-app.js
      timeout-minutes: 1
